# taken from:
# https://github.com/selyunin/gtest_submodule
sudo: required
language: cpp
compiler: gcc

env:
  global:
    # Ubuntu version
    - LINUX_DIST=xenial
    - DEPS_DIR=${TRAVIS_BUILD_DIR}/deps
    # Global build options and C++ flags
    - CXX_FLAGS="-std=c++17 -Wall -pedantic -Werror -Wno-variadic-macros -Wno-long-long -Wno-shadow"
    # Misc
    - RUN_TESTS=true

matrix:
  include:
    - os: linux
      sudo: true
      compiler: gcc
      addons:
        apt:
          packages: &precise_latest_boost_packages
            - gcc-8
            - g++-8
            # - clang-8
            # - valgrind
            # Misc
            # - python-yaml
            # - lcov
            # - libopencv-dev
          sources: &precise_latest_boost_sources
            - ubuntu-toolchain-r-test
          #   - llvm-toolchain-precise-3.7

cache: apt
addons:
  apt:
    packages:
    - libtbb-dev

install:
  # - if [ "$CXX" = "clang++" ] && [ "$TRAVIS_OS_NAME" = "linux" ]; then export CXX="clang++-8" CC="clang-8"; fi
  - echo ${PATH}
  - echo ${CXX}
  - ${CXX} --version
  - ${CXX} -v
  # - sudo pip install codecov
  
  # # Download and install recent cmake
  # - |
  #   if [[ ${TRAVIS_OS_NAME} == "linux" ]]; then
  #   CMAKE_URL="http://www.cmake.org/files/v3.5/cmake-3.5.1-Linux-x86_64.tar.gz"
  #   mkdir -p ${DEPS_DIR}/cmake
  #   travis_retry wget --no-check-certificate --quiet -O - ${CMAKE_URL} | tar --strip-components=1 -xz -C ${DEPS_DIR}/cmake
  #   export PATH=${DEPS_DIR}/cmake/bin:${PATH}
  #   fi

notifications:
  slack: theoptimisationgroup:tRbj8LtmY5KkuyL8qrQ7UOIQ

script:
  ############################################################################
  # Build main and tests
  ############################################################################
  - make clean
  - make test

after_success:
  - echo "SUCCESS"