# taken from:
# https://github.com/selyunin/gtest_submodule
language: cpp
compiler: gcc
os: linux
dist: xenial

env:
  global:
    # Ubuntu version
    - LINUX_DIST=xenial
    - DEPS_DIR=${TRAVIS_BUILD_DIR}/deps
    # Global build options and C++ flags
    - CXX_FLAGS="-std=c++17 -Wall -pedantic -Werror -Wno-variadic-macros -Wno-long-long -Wno-shadow"
    # Misc
    - RUN_TESTS=true

jobs:
  include:
    - os: linux
      compiler: gcc
      addons:
        apt:
          packages: &precise_latest_boost_packages
            - gcc-8
            - g++-8
            # - clang-8
          sources: &precise_latest_boost_sources
            - ubuntu-toolchain-r-test

cache: apt

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - export CMAKE_OPTIONS="${CMAKE_OPTIONS} -DBUILD_TESTS:BOOL=ON  ${ENV_CMAKE_OPTIONS}"
  - export CXX_FLAGS="${CXX_FLAGS} ${ENV_CXX_FLAGS}"
  - sudo apt-get update -qq
  - CC=gcc-8
  - CXX=g++-8

install:
  # - if [ "$CXX" = "clang++" ] && [ "$TRAVIS_OS_NAME" = "linux" ]; then export CXX="clang++-8" CC="clang-8"; fi
  - echo ${PATH}
  - echo ${CXX}
  - ${CXX} --version
  - ${CXX} -v

notifications:
  slack: theoptimisationgroup:tRbj8LtmY5KkuyL8qrQ7UOIQ

script:
  ############################################################################
  # Build main and tests
  ############################################################################
  - mkdir -p build
  - cd build
  - cmake ${CMAKE_OPTIONS} -DCMAKE_CXX_FLAGS=${CXX_FLAGS} ..
  - make
  - ctest

after_success:
  - echo "SUCCESS"
  - ./runBenchmarks