name: CMake

on: [push]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  RUN_TESTS: true
  RUN_BENCHMARKS: true
  BENCHMARK_BRANCHES: refs/heads/master refs/heads/develop
  CC: gcc-8
  CXX: g++-8


jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: true

    - name: Setup cmake
      uses: jwlawson/actions-setup-cmake@v1.9
      with:
        cmake-version: '3.20.*'
      shell: bash
      run:
        cmake --version

    - name: apt-get
      shell: bash
      run: sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test; sudo apt-get install gcc-8 g++-8 python3; sudo apt-get update -qq;

    - name: Build Benchmarks Flag
      id: buildBenchmarksFlag
      with:
        cond: contains(env.BENCHMARK_BRANCHES, github.ref)
        if_true: 'ON'
        if_false: 'OFF'

    - name: Build
      uses: steps.buildBenchmarksFlag
      working-directory: ${{github.workspace}}/build
      env:
        CMAKE_FLAGS: -DBUILD_TESTS:BOOL=ON -DBUILD_BENCHMARKS:BOOL=${{steps.buildBenchmarksFlag.outputs.value}} -DCMAKE_BUILD_TYPE=Debug
      shell: bash
      # Execute the build.  You can specify a specific target with "--target <NAME>"
      run: cmake $CMAKE_OPTIONS $CMAKE_FLAGS -DCMAKE_CXX_FLAGS=$CXX_FLAGS  ..; make

    - name: Test
      working-directory: ${{github.workspace}}/build
      shell: bash
      # Execute tests defined by the CMake configuration.  
      # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
      run: ctest
    
    - name: Slack
      uses: act10ns/slack@v1
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_BUILD }}
      with:
        status: ${{ job.status }}
        steps: ${{ toJson(steps) }}
        channel: '#build'
      if: always()
    
    - name: Run Benchmarks
      #if: contains(env.BENCHMARK_BRANCHES, github.ref)
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_BENCH }}
      shell: bash
      # Execute the build.  You can specify a specific target with "--target <NAME>"
      run: chmod +x ./slack-benchmark.sh; ./slack-benchmark.sh;