name: CMake

on: [push]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  GTEST_BUILD_TYPE: Debug
  DEPS_DIR: ${{github.workspace}}/deps
  CXX_FLAGS: -std=c++17 -Wall -pedantic -Werror -Wno-variadic-macros -Wno-long-long -Wno-shadow
  RUN_TESTS: true
  RUN_BENCHMARKS: true
  BENCHMARK_BRANCHES: refs/heads/feature/gha refs/heads/develop
  CC: gcc-8
  CXX: g++-8


jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: true

    - name: Setup cmake
      uses: jwlawson/actions-setup-cmake@v1.8
      with:
        cmake-version: '3.10.x'

    - name: apt-get
      shell: bash
      run: sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test; sudo apt-get install gcc-8 g++-8 python3; sudo apt-get update -qq;

    - name: Create Build Environment
      # Some projects don't allow in-source building, so create a separate build directory
      # We'll use this as our working directory for all subsequent commands
      run: cmake -E make_directory ${{github.workspace}}/build
    
    - name: Build
      working-directory: ${{github.workspace}}/build
      env:
        CMAKE_FLAGS: -DBUILD_TESTS:BOOL=ON -DBUILD_BENCHMARKS:BOOL=OFF -DCMAKE_BUILD_TYPE=Debug
      shell: bash
      # Execute the build.  You can specify a specific target with "--target <NAME>"
      run: cmake $CMAKE_OPTIONS $CMAKE_FLAGS -DCMAKE_CXX_FLAGS=$CXX_FLAGS  ..; make

    - name: Test
      working-directory: ${{github.workspace}}/build
      shell: bash
      # Execute tests defined by the CMake configuration.  
      # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
      run: ctest
    
    - name: Slack
      uses: act10ns/slack@v1
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_BUILD }}
      with:
        status: ${{ job.status }}
        steps: ${{ toJson(steps) }}
        channel: '#build'
      if: always()
    
    - name: Create Benchmark Environment
      if: contains(${{ env.BENCHMARK_BRANCHES }}, github.ref)
      run: rm -rf ${{github.workspace}}/build; cmake -E make_directory ${{github.workspace}}/build

    - name: Build Benchmarks
      working-directory: ${{github.workspace}}/build
      if: contains(${{ env.BENCHMARK_BRANCHES }}, github.ref)
      env:
        CMAKE_FLAGS: -DBUILD_TESTS:BOOL=OFF -BENCHMARK_ENABLE_TESTING:BOOL=OFF -DBUILD_BENCHMARKS:BOOL=ON -DCMAKE_BUILD_TYPE=Release
      shell: bash
      # Execute the build.  You can specify a specific target with "--target <NAME>"
      run: cmake $CMAKE_OPTIONS $CMAKE_FLAGS -DCMAKE_CXX_FLAGS=$CXX_FLAGS  ..; make

    - name: Run Benchmarks
      if: contains(${{ env.BENCHMARK_BRANCHES }}, github.ref)
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_BENCH }}
      shell: bash
      # Execute the build.  You can specify a specific target with "--target <NAME>"
      run: bash slack-benchmark.sh;